# -*- coding: utf-8 -*-
"""task-2-decodelabs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVTTILGEeJC6ELcXgUQF6qigUaop9z4S
"""

# Install required libraries

!pip install -q pandas scikit-learn

# Import required libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

# Load the dataset
import kagglehub
import os

path = kagglehub.dataset_download("arshid/iris-flower-dataset")
print("Path to dataset files:", path)
csv_path = os.path.join(path, "IRIS.csv")
df = pd.read_csv(csv_path)
df.head(10)

# Explore the dataset

print("Dataset Shape")
print(df.shape)
print()

print("Column Names")
print(df.columns)
print()

print("First Five Rows")
print(df.head())
print()

print("Class Distribution")
print(df["species"].value_counts())

# Prepare features and target
X = df.drop("species", axis=1)
y = df["species"]

# Split the dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

# Scale the features

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the KNN model

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# Predict the test data

predictions = model.predict(X_test)
print(predictions)

# Calculate the accuracy

accuracy = accuracy_score(y_test, predictions)
print("Accuracy")
print(accuracy)

# Generate the confusion matrix

cm = confusion_matrix(y_test, predictions)

print("Confusion Matrix")

print(cm)

# Calculate the F1 score

score = f1_score(
    y_test,
    predictions,
    average="weighted"
)
print("F1 Score")
print(score)